<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js([
    pi::url('static/js/html5shiv.js')   => [
        'conditional' => 'lt IE 9',
    ],
    pi::url('static/js/respond.min.js') => [
        'conditional' => 'lt IE 9',
    ],
]);

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap([
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css',
]);

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink([
    'rel'  => 'apple-touch-icon',
    'href' => $this->assetTheme('image/touch-icon-iphone.png'),
]);
// Apple icon for ipad
$this->headLink([
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png'),
]);
// Apple icon for iphone retina
$this->headLink([
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png'),
]);
// Apple icon for ipad retina
$this->headLink([
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png'),
]);

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink([
    'rel'  => 'shortcut icon',
    'type' => 'image/x-icon',
    'href' => $this->favicon(),
]);
$this->headLink([
    'rel'  => 'shortcut icon',
    'type' => 'image/png',
    'href' => $this->favicon('favicon.png'),
]);

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks        = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    ['prefix' => [
        [
            'label' => __('Home'),
            'href'  => Pi::url($this->url('home')),
        ],
    ]]
);
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front">
<!-- Header: brand, slogan, user bar -->
<?php if ($module == 'system') { ?>
    <header class="pi-header">
        <div class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="active item">
                    <picture>
                        <!--[if IE 9]><video style="display: none;"><![endif]-->
                        <source data-srcset="<?php echo $this->assetTheme('image/header/main-mobi.jpg'); ?>" media="(max-width: 320px)" srcset="<?php echo $this->assetTheme('image/header/main-mobi.jpg'); ?>">
                        <source data-srcset="<?php echo $this->assetTheme('image/header/main-smart.jpg'); ?>" media="(max-width: 480px)" srcset="<?php echo $this->assetTheme('image/header/main-smart.jpg'); ?>">
                        <source data-srcset="<?php echo $this->assetTheme('image/header/main-tab.jpg'); ?>" media="(max-width: 768px)" srcset="<?php echo $this->assetTheme('image/header/main-tab.jpg'); ?>">
                        <source data-srcset="<?php echo $this->assetTheme('image/header/main-lap.jpg'); ?>" media="(max-width: 1366px)" srcset="<?php echo $this->assetTheme('image/header/main-lap.jpg'); ?>">
                        <source data-srcset="<?php echo $this->assetTheme('image/header/main-xlap.jpg'); ?>" media="(max-width: 1920px)" srcset="<?php echo $this->assetTheme('image/header/main-xlap.jpg'); ?>">
                        <source data-srcset="<?php echo $this->assetTheme('image/header/main-desk.jpg'); ?>" media="(max-width: 2880px)" srcset="<?php echo $this->assetTheme('image/header/main-desk.jpg'); ?>">
                        <!--[if IE 9]></video><![endif]-->
                        <img id="pi-header-image" class="img-responsive lazyloaded" data-src="<?php echo $this->assetTheme('image/header/main-xlap.jpg'); ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $this->assetTheme('image/header/main-xlap.jpg'); ?>">
                    </picture>

                </div>
            </div>
        </div>
        <div class="pi-header-body clearfix">
            <nav class="navbar navbar-default">
                <div class="container-inner">
                    <div class="navbar-header">
                        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                        <div class="navbar-brand">
                            <h1>
                                <a href="<?php echo Pi::url($this->url('home')); ?>"
                                   title="<?php echo _escape($sitename); ?>">
                                    <img class="img-responsive" src="<?php echo $this->assetTheme('image/title.png'); ?>"
                                         alt="<?php echo _escape($sitename); ?>">
                                </a>
                            </h1>
                        </div>
                    </div>
                    <div class="navbar-collapse collapse">
                        <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                    </div>
                </div>
            </nav>
            <div class="pi-header-body-content">
                <div class="carousel-inner">
                    <div class="row">
                        <div class="col-md-4 col-md-offset-4 col-xs-12">
                            <div class="text-center">
                                <h3>
                                    <a href="<?php echo Pi::url($this->url('home')); ?>"
                                       title="<?php echo _escape($sitename); ?>">
                                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/logo.png'); ?>"
                                             alt="<?php echo _escape($sitename); ?>">
                                    </a>
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pi-header-body-footer">
                <div class="carousel-inner">
                    <div class="row">
                        <div class="col-md-6 text-left hidden-xs">
                            <h4>چون ثروت ارزشه</h4>
                        </div>
                        <div class="col-md-6 col-xs-12 text-right pi-header-body-footer-box">
                            <a href="https://www.poolafarin.com/ads/click/1/web" title="دانلود اپلیکیشن">
                                <span>دانلود اپلیکیشن </span><i class="fa fa-download"></i>
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="list-inline pi-header-body-footer-line">
                                <li>ما را دنبال کنید</li>
                                <li>
                                    <a title="" href="#">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a title="" href="#">
                                        <i class="fa fa-facebook-square"></i>
                                    </a>
                                </li>
                                <li>
                                    <a title="" href="#">
                                        <i class="fa fa-telegram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a title="" href="#">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
<?php } else { ?>
    <nav class="navbar navbar-default">
        <div class="container-inner">
            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="<?php echo Pi::url($this->url('home')); ?>"
                   title="<?php echo _escape($sitename); ?>">
                    <img class="img-responsive" src="<?php echo $this->assetTheme('image/title.png'); ?>"
                         alt="<?php echo _escape($sitename); ?>">
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                <div class="navbar-right">
                    <ul class="nav navbar-nav pi-navbar-nav download-app">
                        <li>
                            <a href="https://www.poolafarin.com/ads/click/1/web" title="دانلود اپلیکیشن">
                                <i class="fa fa-download"></i>  دانلود اپلیکیشن
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
<?php } ?>
<!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
<?php if ($module == 'system') { ?>
    <section class="pi-section-about">
        <div class="carousel-inner">
            <div class="row clearfix">
                <div class="col-md-7">
                    <div class="pi-section-about-text">
                        <h2>درباره پول آفرین</h2>
                        <h3>پول آفرین، داستان پولدار ها است</h3>
                        <p>با پول آفرین راز پولدار شدن را کشف کنید. در پول آفرین صدها نفر از ثروتمندترین اشخاص ایران در مورد نحوه پولدار شدنشان صحبت میکنند. پول آفرین هر هفته به سراغ افراد ثروتمند در شغل های مختلف میرود و پای صحبت های آنها مینشیند پس با پول آفرین  هزاران راه و انگیزه پولدار شدن را از زبان ثرومندترین های ایران بشنوید با کسب و کارها و سبک زندگی آنها آشنا شوید.دانلود اپلیکیشن پول آفرین میتواند بهترین نقطه شروع کسب ثروت و پولدار شدن در ایران باشد.خیلی از داستان های پولدار شدن در پول آفرین غیر قابل باور و عجیب هستند و شنیدنشان میتواند ذهن شما را به پرواز در بیاورد تا به آرزوهای کسب ثروت و پوادار شدنتان با امید و انگیزه بیشتری بیاندیشید.</p>
                    </div>
                </div>
                <div class="col-md-5 hidden-xs">
                    <div class="pi-section-about-img">
                        <img src="<?php echo $this->assetTheme('image/about.jpg'); ?>" alt="درباره پول آفرین" class="img-responsive">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="pi-section-app">
        <div class="carousel-inner">
            <div class="row">
                <div class="col-md-12">
                    <div class="pi-section-app-img text-center">
                        <img src="<?php echo $this->assetTheme('image/app-info.png'); ?>" alt="اپلیکشن پول آفرین" class="img-responsive">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="pi-section-blog">
        <div class="carousel-inner">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <div class="pi-section-blog-img">
                        <img src="<?php echo $this->assetTheme('image/blog.jpg'); ?>" alt="وبلاگ پول آفرین" class="img-responsive">
                    </div>
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="pi-section-blog-text">
                        <h3>داستان پولدار ترین مردان جهان</h3>
                        <p>علم پول آفرینی رو مطالعه کن</p>
                        <p>در وبلاگ پول آفرین به معرفی پولدارترین های جهان، معرفی کسب و کار آنان و روحیات آنها خواهیم پرداخت. اصول و روش های کسب ثروت را از زبان ثروتمندان و مربیان کسب ثروت و موفقیت در جهان ارائه خواهیم کرد و از لحاظ علمی به بررسی عوامل ثروتمند شدن خواهیم پرداخت</p>
                        <div class="pi-section-blog-btn">
                            <a class="btn btn-primary btn-lg" href="https://www.poolafarin.com/news">وبلاگ</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php } else { ?>
    <section class="pi-section">
        <div class="carousel-inner">
            <div class="pi-main-container">
                <?php if ($breadcrumbs) {
                    echo $breadcrumbs;
                } ?>
                <!-- Flash messenger -->
                <?php include $this->template('flash-messenger'); ?>
                <!-- Top head zone -->
                <?php if (!empty($blocks['0'])) { ?>
                    <div class="pi-zone-0">
                        <?php foreach ($blocks['0'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="row">
                    <!-- Left zone -->
                    <?php if (!empty($blocks['1'])) { ?>
                        <div class="pi-zone-1 col-md-4">
                            <?php foreach ($blocks['1'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <div class="<?php
                    if (isset($blocks['1']) && isset($blocks['8'])) {
                        echo 'col-md-4';
                    } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                        echo 'col-md-8';
                    } else {
                        echo 'col-md-12';
                    }
                    ?>">
                        <!-- Center top zone -->
                        <?php if (isset($blocks['2'])) { ?>
                            <div class="pi-zone-2">
                                <?php foreach ($blocks['2'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                        <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-3">
                                    <?php
                                    if (isset($blocks['3'])) {
                                        foreach ($blocks['3'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-4">
                                    <?php
                                    if (isset($blocks['4'])) {
                                        foreach ($blocks['4'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Module content starts -->
                        <?php if (!empty($content)) { ?>
                            <div class="<?php echo $module; ?>">
                                <div class="pi-module-content" data-ng-app="<?php echo $module; ?>">
                                    <?php echo $content; ?>
                                </div>
                                <?php echo Pi::service('comment')->load(['options' => ['type' => 'js']]); ?>
                            </div>
                        <?php } ?>
                        <!-- Module content ends -->
                        <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-5">
                                    <?php
                                    if (isset($blocks['5'])) {
                                        foreach ($blocks['5'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-6">
                                    <?php
                                    if (isset($blocks['6'])) {
                                        foreach ($blocks['6'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Center bottom zone -->
                        <?php if (isset($blocks['7'])) { ?>
                            <div class="pi-zone-7">
                                <?php foreach ($blocks['7'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                    </div>
                    <!-- Right zone -->
                    <?php if (isset($blocks['8'])) { ?>
                        <div class="col-md-4 pi-zone-8">
                            <?php foreach ($blocks['8'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- Bottom foot zone -->
                <?php if (isset($blocks['99'])) { ?>
                    <div class="pi-zone-99">
                        <?php foreach ($blocks['99'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </section>
<?php } ?>
<!-- Footer: sitelink -->
<footer class="pi-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="text-center col-md-12 col-xs-12" data-rel="license"> تمام حقوق مطالب برای وب سایت <a title="<?php echo _escape($sitename); ?>" href="https://www.poolafarin.com"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
        </div>
    </div>
</footer>
</body>
</html>